$background = 130d0e
$onBackground = f6e0e5
$surface = 130d0e
$surfaceDim = 130d0e
$surfaceBright = 35292c
$surfaceContainerLowest = 000000
$surfaceContainerLow = 191114
$surfaceContainer = 20171a
$surfaceContainerHigh = 271d20
$surfaceContainerHighest = 2f2226
$onSurface = f6e0e5
$surfaceVariant = 2f2226
$onSurfaceVariant = baa6ab
$outline = 827175
$outlineVariant = 534448
$inverseSurface = fff8f8
$inverseOnSurface = 5c5355
$shadow = 000000
$scrim = 000000
$surfaceTint = f2b6c9
$primary = f2b6c9
$primaryDim = e3a9bb
$onPrimary = 5e3342
$primaryContainer = 724555
$onPrimaryContainer = ffdae4
$inversePrimary = 805161
$primaryFixed = fec1d4
$primaryFixedDim = efb4c6
$onPrimaryFixed = 502836
$onPrimaryFixedVariant = 704353
$secondary = e2bdc7
$secondaryDim = d4afb9
$onSecondary = 533941
$secondaryContainer = 4e343c
$onSecondaryContainer = dbb6c0
$secondaryFixed = ffd9e3
$secondaryFixedDim = f1cbd5
$onSecondaryFixed = 523840
$onSecondaryFixedVariant = 71545c
$tertiary = ffe7fd
$tertiaryDim = fdd2fe
$onTertiary = 6e4d71
$tertiaryContainer = fdd2fe
$onTertiaryContainer = 654568
$tertiaryFixed = fdd2fe
$tertiaryFixedDim = eec4ef
$onTertiaryFixed = 513355
$onTertiaryFixedVariant = 6f4e72
$error = f97386
$errorDim = c44b5f
$onError = 490013
$errorContainer = 871c34
$onErrorContainer = ff97a3
$primaryPaletteKeyColor = 9b6979
$secondaryPaletteKeyColor = 8e6f78
$tertiaryPaletteKeyColor = 8e6b91
$neutralPaletteKeyColor = 7f7476
$neutralVariantPaletteKeyColor = 847377
$errorPaletteKeyColor = c74d61
$primary_paletteKeyColor = 9b6979
$secondary_paletteKeyColor = 8e6f78
$tertiary_paletteKeyColor = 8e6b91
$neutral_paletteKeyColor = 7f7476
$neutral_variant_paletteKeyColor = 847377
$term0 = 353434
$term1 = ff4c89
$term2 = ffbbb7
$term3 = ffdedf
$term4 = b3a2d5
$term5 = ea8fb0
$term6 = ffba93
$term7 = efd1d2
$term8 = b39e9e
$term9 = ff81a2
$term10 = ffd3d0
$term11 = fff1f0
$term12 = dcbc93
$term13 = f9a8c1
$term14 = ffd1c0
$term15 = ffffff
$rosewater = ffedef
$flamingo = fcd9e0
$pink = ffd1e1
$mauve = ffa4d4
$red = fc94b7
$maroon = f3aabf
$peach = ffbcc5
$yellow = ffedec
$green = ffd8c5
$teal = dedcff
$sky = ebd1ff
$sapphire = f2b2f2
$blue = f4a3de
$lavender = ffb7e4
$klink = b76ead
$klinkSelection = b76ead
$kvisited = c45d96
$kvisitedSelection = c45d96
$knegative = e84f88
$knegativeSelection = e84f88
$kneutral = ff859d
$kneutralSelection = ff859d
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = f6e0e5
$subtext1 = baa6ab
$subtext0 = 827175
$overlay2 = 726366
$overlay1 = 615457
$overlay0 = 524649
$surface2 = 43383b
$surface1 = 342b2d
$surface0 = 231c1d
$base = 130d0e
$mantle = 130d0e
$crust = 120c0d
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
