#---------------------------------------------------------------------------------------
#   All file contain in Modules Folders
#---------------------------------------------------------------------------------------

# Monitors resolution, scale and position settings
monitor=eDP-1,1920x1080@60,0x0,1

# all env and variable file
source = ~/.config/hypr/Modules/env&Vars.conf

# Autostart Programs & Script
source = ~/.config/hypr/Modules/exec.conf

# Layout related Files
source = ~/.config/hypr/Modules/Layout.conf

# Inuts and devices Settings
 source = ~/.config/hypr/Modules/Devices.conf                           

# Animations file
source = ~/.config/hypr/Modules/animation.conf

# All keybinds
source = ~/.config/hypr/Modules/keybinds.conf

#  All Windows Rules
 source = ~/.config/hypr/Modules/Windowrules.conf

#Create a sparated file for plugins config and included it here
#source = ~/.config/hypr/plugins.conf

#---------------------------------------------------------------------------------------
#  Ends Of the file
#---------------------------------------------------------------------------------------

