-- AUTO-GENERATED BY MATUGEN
-- DO NOT EDIT MANUALLY

local M = {}

M.palette = {
  -- Base16
  base00 = "#111318",
  base01 = "#0c0e13",
  base02 = "#191c20",
  base03 = "#43474e",
  base04 = "#c4c6cf",
  base05 = "#e1e2e9",
  base06 = "#2e3035",
  base07 = "#37393e",

  base08 = "#ffb4ab",
  base09 = "#dabde2",
  base0A = "#bdc7dc",
  base0B = "#a6c8ff",
  base0C = "#553f5d",
  base0D = "#234776",
  base0E = "#3d4758",
  base0F = "#93000a",
}

return M
