-- AUTO-GENERATED BY MATUGEN
-- DO NOT EDIT MANUALLY

local M = {}

M.palette = {
  -- Base16
  base00 = "#111418",
  base01 = "#0c0e13",
  base02 = "#191c20",
  base03 = "#43474e",
  base04 = "#c3c6cf",
  base05 = "#e1e2e8",
  base06 = "#2e3035",
  base07 = "#37393e",

  base08 = "#ffb4ab",
  base09 = "#d8bde3",
  base0A = "#bbc7db",
  base0B = "#a3c9fe",
  base0C = "#533f5e",
  base0D = "#1e4875",
  base0E = "#3c4758",
  base0F = "#93000a",
}

return M
