# Other settings of gaps, colors and border of windows
general {
    gaps_in = 2
    gaps_out = 4
    border_size = 2
    col.active_border = rgba($primarye6) rgba($tertiarycc) 45deg
    col.inactive_border = rgba($surfaceVariant55)

    resize_on_border = false

    allow_tearing = false
    layout = scrolling
}

decoration {
    rounding = 7
    rounding_power = 3

    active_opacity = 1.0
    inactive_opacity = 0.96

    shadow {
        enabled = true
        range = 8
        render_power = 2
        color = rgba($shadow55)
    }

    blur {
        enabled = true
        size = 4
        passes = 2
        vibrancy = 0.2
    }
}

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

master {
    new_status = master
}

scrolling {
        column_width = 0.5
        fullscreen_on_one_column = true
        focus_fit_method = 1
        explicit_column_widths = 0.5,1.0
        follow_focus = false
    #        direction = left
}
