-- return {
--     -- Mason Installer UI
--     {
--         "williamboman/mason.nvim",
--         config = function()
--             require("mason").setup()
--         end,
--     },
--
--     -- Bridge between Mason and LSPConfig
--     {
--         "williamboman/mason-lspconfig.nvim",
--         config = function()
--             require("mason-lspconfig").setup({
--                 ensure_installed = {
--                     "lua_ls",
--                     "ts_ls",
--                     "solargraph",
--                     "ruby_lsp",
--                     "tailwindcss",
--                 },
--             })
--         end,
--     },
--
--     -- Main LSP Configuration
--     {
--         "neovim/nvim-lspconfig",
--         config = function()
--             local lspconfig = require("lspconfig")
--
--             -- Lua LSP
--             lspconfig.lua_ls.setup({})
--
--             -- TypeScript/JavaScript LSP
--             lspconfig.ts_ls.setup({})
--
--             -- Ruby LSPs
--             lspconfig.solargraph.setup({})
--             lspconfig.ruby_lsp.setup({})
--
--             -- Tailwind CSS LSP
--             lspconfig.tailwindcss.setup({
--                 filetypes = {
--                     "html",
--                     "css",
--                     "scss",
--                     "javascript",
--                     "typescript",
--                     "javascriptreact",
--                     "typescriptreact",
--                     "svelte",
--                     "vue",
--                 },
--                 init_options = {
--                     userLanguages = {
--                         eruby = "html",
--                     },
--                 },
--             })
--         end,
--     },
--     {
--         "nvimtools/none-ls.nvim",
--         config = function()
--             local null_ls = require("null-ls")
--
--             null_ls.setup({
--                 sources = {
--                     -- ✅ Formatters
--                     null_ls.builtins.formatting.stylua,   -- Lua
--                     null_ls.builtins.formatting.prettier, -- JS, TS, JSX, TSX, JSON, CSS, HTML
--                     null_ls.builtins.formatting.rubocop,  -- Ruby
--                     null_ls.builtins.formatting.fixjson,  -- JSON
--
--                     -- ✅ Linters
--                     null_ls.builtins.diagnostics.rubocop, -- Ruby lint
--                     null_ls.builtins.diagnostics.eslint,  -- JS/TS lint
--                     null_ls.builtins.diagnostics.erblint, -- ERB
--                 },
--             })
--         end,
--     },
-- }
--
return {}
